# Copyright (c) 2026 Pointmatic
# SPDX-License-Identifier: Apache-2.0
"""FR-17 deterministic scaffolder tests (Story C.o)."""

from __future__ import annotations

import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from PIL import Image

from datarefinery.core.errors import PluginError, RecipeError
from datarefinery.recipe.loader import load
from datarefinery.recipe.validator import validate
from datarefinery.scaffolder import init as scaffolder_init
from datarefinery.scaffolder.init import (
    scaffold,
    scaffold_image_classification,
)


def _build_image_folder(
    root: Path,
    *,
    classes: tuple[str, ...] = ("cats", "dogs"),
    per_class: int = 5,
    size: int = 8,
) -> Path:
    rng = np.random.default_rng(0)
    for cls in classes:
        cls_dir = root / cls
        cls_dir.mkdir(parents=True, exist_ok=True)
        for i in range(per_class):
            arr = rng.integers(0, 255, (size, size, 3), dtype=np.uint8)
            Image.fromarray(arr).save(cls_dir / f"{cls}_{i:03d}.png")
    return root


# ---------------------------------------------------------------------------
# Deterministic image_classification scaffolder
# ---------------------------------------------------------------------------


def test_scaffold_inspects_image_folder_and_writes_recipe(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    assert out.exists()
    content = out.read_text()
    assert content.startswith("# Generated by datarefinery scaffolder")
    assert "schema_version: 1" in content
    assert "plugin: image_classification" in content


def test_scaffolded_recipe_loads_and_validates_clean(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)

    from datarefinery.plugins.image_classification import PLUGIN as IMAGE_PLUGIN

    recipe = load(out)
    report = validate(recipe, IMAGE_PLUGIN)
    assert report.passed, [r for r in report.failures]


def test_scaffolded_recipe_inspects_image_dims(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data", size=24)
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    recipe = load(out)
    spec = recipe.Output.record_schema["image"]
    assert spec.shape == [24, 24, 3]
    assert spec.dtype == "uint8"


def test_scaffolded_recipe_uses_70_15_15_split(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    recipe = load(out)
    assert recipe.Splits.ratios == {"train": 0.7, "val": 0.15, "test": 0.15}
    assert recipe.Splits.stratify_by == "label"
    assert recipe.Splits.seed == 11


def test_scaffolded_recipe_includes_label_from_path_featurization(
    tmp_path: Path,
) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    recipe = load(out)
    assert any(
        f.op == "label_from_path" and f.output_field == "label" for f in recipe.Featurizations
    )


def test_scaffolded_recipe_includes_reporting_visualizations(
    tmp_path: Path,
) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    recipe = load(out)
    ops = {v.op for v in recipe.Visualizations if v.mode == "reporting"}
    assert {"class_distribution_histogram", "sample_grid"}.issubset(ops)


def test_scaffolded_recipe_uses_derived_label_source(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    recipe = load(out)
    assert recipe.Labels.source.kind == "derived"
    assert recipe.Labels.source.derivation == "parent_directory_name"


def test_scaffolded_recipe_yaml_includes_suggested_transformations(
    tmp_path: Path,
) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    content = out.read_text()
    # Commented-out suggestions present.
    assert "# Suggested Transformations" in content
    assert "#   - name: resize" in content
    assert "#   - name: normalize" in content


def test_scaffolder_creates_parent_dirs_for_output(tmp_path: Path) -> None:
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "deep" / "nested" / "recipe.yaml"
    scaffold_image_classification(input_path, out)
    assert out.exists()


# ---------------------------------------------------------------------------
# Refusals: non-image plugins, bad inputs
# ---------------------------------------------------------------------------


def test_scaffold_tabular_raises_documented_refusal(tmp_path: Path) -> None:
    with pytest.raises(PluginError, match="not available for this category"):
        scaffold(tmp_path, tmp_path / "out.yaml", plugin="tabular")


def test_scaffold_text_raises_documented_refusal(tmp_path: Path) -> None:
    with pytest.raises(PluginError, match="not available for this category"):
        scaffold(tmp_path, tmp_path / "out.yaml", plugin="text")


def test_scaffold_default_plugin_is_image_classification(tmp_path: Path) -> None:
    """Default ``plugin=`` argument should not refuse for image folders."""
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold(input_path, out)
    assert out.exists()


def test_input_not_a_directory_raises(tmp_path: Path) -> None:
    target = tmp_path / "notadir.txt"
    target.write_text("hello")
    with pytest.raises(RecipeError, match="not a directory"):
        scaffold_image_classification(target, tmp_path / "out.yaml")


def test_input_empty_directory_raises(tmp_path: Path) -> None:
    empty = tmp_path / "empty"
    empty.mkdir()
    with pytest.raises(RecipeError, match="no class subdirectories"):
        scaffold_image_classification(empty, tmp_path / "out.yaml")


def test_input_with_class_dirs_but_no_images_raises(tmp_path: Path) -> None:
    root = tmp_path / "data"
    (root / "cats").mkdir(parents=True)
    (root / "dogs").mkdir(parents=True)
    with pytest.raises(RecipeError, match="no image files"):
        scaffold_image_classification(root, tmp_path / "out.yaml")


# ---------------------------------------------------------------------------
# LLM enhancement layer: lazy import, offline behavior
# ---------------------------------------------------------------------------


def test_enhance_without_lmentry_raises_plugin_error(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # Block `import lmentry` even if it happens to be installed in the
    # test environment.
    monkeypatch.setitem(sys.modules, "lmentry", None)
    input_path = _build_image_folder(tmp_path / "data")
    with pytest.raises(PluginError, match=r"\[llm\]"):
        scaffold_image_classification(input_path, tmp_path / "recipe.yaml", enhance=True)


def test_enhance_offline_emits_skipped_note(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # Inject a fake `lmentry` module so the ImportError path doesn't fire.
    fake_module = type(sys)("lmentry")
    monkeypatch.setitem(sys.modules, "lmentry", fake_module)
    # Force offline.
    from datarefinery.scaffolder import llm as llm_module

    monkeypatch.setattr(llm_module, "_is_online", lambda: False)

    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out, enhance=True)
    content = out.read_text()
    assert "LLM enhancement skipped: offline" in content


def test_enhance_online_emits_applied_note(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fake_module = type(sys)("lmentry")
    monkeypatch.setitem(sys.modules, "lmentry", fake_module)
    from datarefinery.scaffolder import llm as llm_module

    monkeypatch.setattr(llm_module, "_is_online", lambda: True)

    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out, enhance=True)
    content = out.read_text()
    assert "LLM enhancement applied" in content


def test_deterministic_path_does_not_import_lmentry(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Per FR-17: the deterministic path never touches lmentry. Block any
    such import and confirm the scaffolder still works."""
    # Replace `lmentry` in sys.modules with None so an import attempt fails.
    monkeypatch.setitem(sys.modules, "lmentry", None)
    input_path = _build_image_folder(tmp_path / "data")
    out = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, out, enhance=False)
    assert out.exists()


# ---------------------------------------------------------------------------
# Materialize round-trip: scaffolded recipe + synthetic records -> instance
# ---------------------------------------------------------------------------


def _records_for_scaffolded_paths(input_path: Path, *, image_size: int = 8) -> list[dict[str, Any]]:
    """Synthesize records matching the on-disk layout the scaffolder
    inspected. Image bytes are loaded; the runner itself doesn't yet
    do disk loading (deferred from C.m), so we hand the loaded records
    in."""
    out: list[dict[str, Any]] = []
    rec_id = 0
    for cls_dir in sorted(p for p in input_path.iterdir() if p.is_dir()):
        for img_path in sorted(cls_dir.glob("*.png")):
            arr = np.asarray(Image.open(img_path))
            out.append(
                {
                    "record_id": f"rec_{rec_id:04d}",
                    "image": arr,
                    "path": str(img_path),
                }
            )
            rec_id += 1
    return out


def test_scaffolded_recipe_materializes_through_runner(tmp_path: Path) -> None:
    """Story checklist: scaffolded recipe materializes successfully on a
    CIFAR-shaped fixture. Disk-based input loading defers from C.m, so
    we synthesize the records the runner expects from the scaffolded
    on-disk layout."""
    import hashlib

    from datarefinery.cache.layout import (
        manifest_path,
        report_dir,
    )
    from datarefinery.cache.layout import (
        tmp_dir as tmp_dir_for,
    )
    from datarefinery.core.config import RuntimeConfig
    from datarefinery.pipeline.runner import PipelineRunner
    from datarefinery.plugins.image_classification import PLUGIN as IMAGE_PLUGIN

    input_path = _build_image_folder(
        tmp_path / "data", classes=("cats", "dogs", "fish"), per_class=8
    )
    recipe_path = tmp_path / "recipe.yaml"
    scaffold_image_classification(input_path, recipe_path)

    recipe = load(recipe_path)
    records = _records_for_scaffolded_paths(input_path)
    payload = ";".join(sorted(r["record_id"] for r in records))
    input_hashes: Mapping[str, str] = {"train": hashlib.sha256(payload.encode()).hexdigest()}

    cache_root = tmp_path / "cache"
    runner = PipelineRunner(
        recipe=recipe,
        plugin=IMAGE_PLUGIN,
        config=RuntimeConfig(cache_root=cache_root),
        seed=recipe.seed,
    )
    temp = tmp_dir_for(cache_root, "run-1")
    result = runner.run(temp, raw_records=records, raw_input_hashes=input_hashes)
    assert result.cache_hit is False
    assert manifest_path(result.instance_dir).exists()
    # Reporting visualizations from the scaffolded recipe rendered.
    assert (report_dir(result.instance_dir) / "visualizations" / "class_distribution.png").exists()
    assert (report_dir(result.instance_dir) / "visualizations" / "samples.png").exists()
    # Each record acquired a derived label.
    counts = result.manifest.record_counts
    assert sum(counts.values()) == len(records)


# ---------------------------------------------------------------------------
# Module surface
# ---------------------------------------------------------------------------


def test_module_exposes_expected_entry_points() -> None:
    assert callable(scaffolder_init.scaffold)
    assert callable(scaffolder_init.scaffold_image_classification)
